ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ output: 'immersiveengineering:alloybrick'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/treated_wood_horizontal'})
    IRRebirth.remove({ output: 'immersiveengineering:hammer'})
    IRRebirth.remove({ output: 'immersiveengineering:stick_iron', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ output: 'immersiveengineering:stick_steel', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ output: 'immersiveengineering:stick_aluminum', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/cokebrick'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/blastbrick'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/blastbrick_reinforced'})
    IRRebirth.remove({ output: 'immersiveengineering:blastbrick_reinforced', type: 'create:item_application'})
    IRRebirth.remove({ output: 'immersiveengineering:waterwheel_segment'})
    IRRebirth.remove({ output: 'immersiveengineering:watermill'})
    IRRebirth.remove({ output: 'immersiveengineering:hemp_fabric'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_constantan'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_iron'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_electrum'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_copper'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_aluminum'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_lead'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_silver'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_nickel'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_uranium'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_steel'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/sheetmetal_gold'})
    IRRebirth.remove({ output: 'immersiveengineering:windmill'})
    IRRebirth.remove({ output: 'immersiveengineering:windmill_blade'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/steel_scaffolding_standard'})
    IRRebirth.remove({ output: 'immersiveengineering:light_engineering'})
    IRRebirth.remove({ output: 'immersiveengineering:heavy_engineering'})
    IRRebirth.remove({ output: 'immersiveengineering:rs_engineering'})
    IRRebirth.remove({ output: 'immersiveengineering:fluid_pipe'})
    IRRebirth.remove({ output: 'immersiveengineering:generator'})
    IRRebirth.remove({ output: 'immersiveengineering:radiator' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/redstone_acid'})
    IRRebirth.remove({ output: 'draconicevolution:draconium_dust', type: 'immersiveengineering:arc_furnace'})
    IRRebirth.remove({ input: '#forge:ores/draconium', type: 'immersiveengineering:crusher'})
})