ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ output: 'immersiveengineering:alloybrick'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/treated_wood_horizontal'})
    IRRebirth.remove({ output: 'immersiveengineering:hammer'})
    IRRebirth.remove({ output: 'immersiveengineering:stick_iron', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ output: 'immersiveengineering:stick_steel', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ output: 'immersiveengineering:stick_aluminum', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/cokebrick'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/blastbrick'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/blastbrick_reinforced'})
    IRRebirth.remove({ output: 'immersiveengineering:blastbrick_reinforced', type: 'create:item_application'})
})