ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.immersiveengineeringMetalPress(Item.of('kubejs:fluix_wire', 2), 'ae2:fluix_crystal', 'immersiveengineering:mold_wire')
    IRRebirth.recipes.immersiveengineeringMetalPress(Item.of('kubejs:certus_wire', 2), '#forge:gems/certus_quartz', 'immersiveengineering:mold_wire')
    IRRebirth.recipes.immersiveengineeringMetalPress('kubejs:fluix_plate', 'ae2:fluix_crystal', 'immersiveengineering:mold_plate')
    IRRebirth.recipes.immersiveengineeringMetalPress('kubejs:certus_plate', '#forge:gems/certus_quartz', 'immersiveengineering:mold_plate')
    IRRebirth.recipes.immersiveengineeringMetalPress('createdeco:andesite_sheet', 'create:andesite_alloy', 'immersiveengineering:mold_plate')
    IRRebirth.recipes.immersiveengineeringMetalPress('kubejs:graphite_plate', '#forge:ingots/hop_graphite', 'immersiveengineering:mold_plate')
    IRRebirth.recipes.immersiveengineeringMetalPress(Item.of('kubejs:refined_obsidian_rod', 2), '#forge:ingots/refined_obsidian', 'immersiveengineering:mold_rod')
    IRRebirth.recipes.immersiveengineeringMetalPress(Item.of('kubejs:refined_glowstone_rod', 2), '#forge:ingots/refined_glowstone', 'immersiveengineering:mold_rod')
    IRRebirth.recipes.immersiveengineeringMetalPress(Item.of('kubejs:diamond_rod', 2), '#forge:gems/diamond', 'immersiveengineering:mold_rod')
    IRRebirth.recipes.immersiveengineeringMetalPress('kubejs:diamond_plate', '#forge:gems/diamond', 'immersiveengineering:mold_plate')
    IRRebirth.recipes.immersiveengineeringMetalPress('createdeco:netherite_sheet', '#forge:ingots/netherite', 'immersiveengineering:mold_plate')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_copper', '#forge:plates/copper', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_aluminum', '#forge:plates/aluminum', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_lead', '#forge:plates/lead', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_silver', '#forge:plates/silver', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_nickel', '#forge:plates/nickel', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_uranium', '#forge:plates/uranium', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_constantan', '#forge:plates/constantan', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_electrum', '#forge:plates/electrum', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_steel', '#forge:plates/steel', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_iron', '#forge:plates/iron', 'immersiveengineering:mold_packing_4')
    IRRebirth.recipes.immersiveengineeringMetalPress('immersiveengineering:sheetmetal_gold', '#forge:plates/gold', 'immersiveengineering:mold_packing_4')
})