ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_iron' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_gold' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_osmium' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_copper' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_tin' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_lead' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_uranium' })
    IRRebirth.remove({ output: '#forge:dusts', type: "minecraft:crafting_shapeless"})
    IRRebirth.remove({ output: '#forge:plates', type: "minecraft:crafting_shapeless"})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_iron' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_gold' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_osmium' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_copper' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_tin' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_lead' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_uranium' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_aluminum' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_aluminum' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_silver' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_silver' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_nickel' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_nickel' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/raw_hammercrushing_zinc' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/hammercrushing_zinc' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/wire_copper' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/wire_electrum' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/wire_aluminum' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/wire_steel' })
    IRRebirth.remove({ id: 'immersiveengineering:crafting/wire_lead' })
    IRRebirth.remove({ id: 'jaopca:immersiveengineering.plate_to_wire.lead' })
    IRRebirth.remove({ id: 'jaopca:immersiveengineering.plate_to_wire.iron' })
    IRRebirth.remove({ id: 'jaopca:immersiveengineering.plate_to_wire.gold' })
})