ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ input: '#forge:ores/draconium', type: 'minecraft:smelting'})
    IRRebirth.remove({ input: 'jaopca:create_crushed.draconium'})
    IRRebirth.remove({ input: '#forge:ores/draconium', type: 'immersiveengineering:arc_furnace'})
    IRRebirth.remove({ output: 'draconicevolution:draconium_ingot', type: 'minecraft:smelting'})
    IRRebirth.remove({ output: 'draconicevolution:magnet'})
    IRRebirth.remove({ output: 'draconicevolution:advanced_magnet'})
    IRRebirth.remove({ id: 'jaopca:mekanism.ore_to_clump.draconium'})
    IRRebirth.remove({ id: 'jaopca:mekanism.ore_to_shard.draconium'})
    IRRebirth.remove({ output: 'draconicevolution:grinder'})
    IRRebirth.remove({ output: 'draconicevolution:generator'})
    IRRebirth.remove({ output: 'draconicevolution:draconium_chest'})
    IRRebirth.remove({ output: 'draconicevolution:p2p_dislocator_unbound'})
    IRRebirth.remove({ output: 'draconicevolution:dislocator'})
    IRRebirth.remove({ output: 'draconicevolution:potentiometer'})
    IRRebirth.remove({ output: 'draconicevolution:rain_sensor'})
    IRRebirth.remove({ output: 'draconicevolution:dislocator_pedestal'})
    IRRebirth.remove({ output: 'draconicevolution:dislocator_receptacle'})
    IRRebirth.remove({ output: 'draconicevolution:celestial_manipulator'})
    IRRebirth.remove({ output: 'draconicevolution:entity_detector'})
    IRRebirth.remove({ output: 'draconicevolution:entity_detector_advanced'})
    IRRebirth.remove({ output: 'draconicevolution:player_dislocator_unbound'})
    IRRebirth.remove({ output: 'draconicevolution:dislocation_inhibitor'})
    IRRebirth.remove({ output: 'draconicevolution:advanced_dislocator'})
})