ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ input: '#forge:ores/draconium', type: 'minecraft:smelting'})
    IRRebirth.remove({ input: 'jaopca:create_crushed.draconium'})
    IRRebirth.remove({ input: '#forge:ores/draconium', type: 'immersiveengineering:arc_furnace'})
    IRRebirth.remove({ output: 'draconicevolution:draconium_ingot', type: 'minecraft:smelting'})
    IRRebirth.remove({ output: 'draconicevolution:magnet'})
    IRRebirth.remove({ output: 'draconicevolution:advanced_magnet'})
    IRRebirth.remove({ id: 'jaopca:mekanism.ore_to_clump.draconium'})
    IRRebirth.remove({ id: 'jaopca:mekanism.ore_to_shard.draconium'})
    IRRebirth.remove({ output: 'draconicevolution:grinder'})
    IRRebirth.remove({ output: 'draconicevolution:generator'})
    IRRebirth.remove({ output: 'draconicevolution:draconium_chest'})
})