ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_constantan', Item.of('immersiveengineering:plate_constantan', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_iron', Item.of('immersiveengineering:plate_iron', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_electrum', Item.of('immersiveengineering:plate_electrum', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_copper', Item.of('immersiveengineering:plate_copper', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_aluminum', Item.of('immersiveengineering:plate_aluminum', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_lead', Item.of('immersiveengineering:plate_lead', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_silver', Item.of('immersiveengineering:plate_silver', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_nickel', Item.of('immersiveengineering:plate_nickel', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_uranium', Item.of('immersiveengineering:plate_uranium', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_steel', Item.of('immersiveengineering:plate_steel', 2)).heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_gold', Item.of('immersiveengineering:plate_gold', 2)).heated()
    IRRebirth.recipes.create.compacting(Fluid.of('create_dd:sap', 1000), '#minecraft:logs').heated()
})