ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_constantan', '4x #forge:plates/constantan').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_iron', '4x #forge:plates/iron').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_electrum', '4x #forge:plates/electrum').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_copper', '4x #forge:plates/copper').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_aluminum', '4x #forge:plates/aluminum').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_lead', '4x #forge:plates/lead').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_silver', '4x #forge:plates/silver').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_nickel', '4x #forge:plates/nickel').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_uranium', '4x #forge:plates/uranium').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_steel', '4x #forge:plates/steel').heated()
    IRRebirth.recipes.create.compacting('immersiveengineering:sheetmetal_gold', '4x #forge:plates/gold').heated()
    IRRebirth.recipes.create.compacting(Fluid.of('create_dd:sap', 1000), '#minecraft:logs').superheated()
    IRRebirth.recipes.create.compacting(Fluid.of('create_dd:sap', 500), 'create_dd:crystallized_sap').superheated()
    IRRebirth.recipes.create.compacting('create_dd:crystallized_sap', Fluid.of('create_dd:sap', 500)).superheated().id('create_dd:compacting/crystallized_sap')
})