ServerEvents.recipes(IRRebirth => {
  IRRebirth.replaceInput({ output: 'create:copper_backtank' },'minecraft:copper_ingot','#forge:plates/copper')
  IRRebirth.replaceInput({ output: 'create:copper_backtank' },'create:andesite_alloy','#forge:plates/andesite_alloy')
  IRRebirth.replaceInput({ output: 'create:copper_backtank' },'minecraft:copper_block','create_sa:hydraulic_engine')
  IRRebirth.replaceInput({ output: 'create:schematic_table' },'#minecraft:wooden_slabs','#forge:treated_wood_slab')
  IRRebirth.replaceInput({ output: 'create:schematicannon' },'#minecraft:logs','#forge:treated_wood')
  IRRebirth.replaceInput({ output: 'create:white_sail' },'#forge:rods/wooden','immersiveengineering:stick_treated')
  IRRebirth.replaceInput({ output: 'create:mechanical_drill'}, 'minecraft:iron_ingot', '#forge:storage_blocks/iron')
  IRRebirth.replaceInput({input: 'create_dd:bronze_ingot'}, 'create_dd:bronze_ingot', '#forge:ingots/bronze')
  IRRebirth.replaceInput({input: 'create_dd:bronze_sheet'},'create_dd:bronze_sheet', '#forge:plates/bronze')
  IRRebirth.replaceInput({input: 'create_dd:bronze_block'}, 'create_dd:bronze_block', '#forge:storage_blocks/bronze')
  IRRebirth.replaceInput({input: 'create_dd:bronze_nugget'}, 'create_dd:bronze_nugget', '#forge:nuggets/bronze')
  IRRebirth.replaceInput({output: 'createsifter:sifter'}, '#minecraft:planks', '#forge:treated_wood')
  IRRebirth.replaceInput({output: 'createsifter:sifter'}, '#forge:rods/wooden','immersiveengineering:stick_treated')
  IRRebirth.replaceInput({output: 'create_mechanical_extruder:mechanical_extruder' },'#c:glass_blocks','immersiveengineering:insulating_glass')
  IRRebirth.replaceInput({input: 'createdeco:industrial_iron_ingot'}, 'createdeco:industrial_iron_ingot', '#forge:ingots/industrial_iron')
  IRRebirth.replaceInput({input: 'createdeco:industrial_iron_sheet'}, 'createdeco:industrial_iron_sheet', '#forge:plates/industrial_iron')
  IRRebirth.replaceInput({input: 'createdeco:industrial_iron_nugget'}, 'createdeco:industrial_iron_nugget', '#forge:nuggets/industrial_iron')
  IRRebirth.replaceInput({input: 'create_dd:industrial_iron_block'}, 'create_dd:industrial_iron_block', '#forge:storage_blocks/industrial_iron')
  IRRebirth.replaceInput({input: 'create:brass_sheet'}, 'create:brass_sheet', '#forge:plates/brass')
  IRRebirth.replaceInput({input: 'create:copper_sheet'}, 'create:copper_sheet', '#forge:plates/copper')
  IRRebirth.replaceInput({input: 'create:iron_sheet'}, 'create:iron_sheet', '#forge:plates/iron')
  IRRebirth.replaceInput({input: 'createdeco:andesite_sheet'}, 'createdeco:andesite_sheet', '#forge:plates/andesite_alloy')
  IRRebirth.replaceInput({input: 'create_dd:andesite_sheet'}, 'create_dd:andesite_sheet', '#forge:plates/andesite_alloy')
  IRRebirth.replaceInput({output: '/steampowered:.*/'}, '#steampowered:bronze', '#forge:ingots/bronze')
  IRRebirth.replaceInput({output: '/steampowered:.*/'}, '#steampowered:bronzeplate', '#forge:plates/bronze')
  IRRebirth.replaceInput({output: '/steampowered:cast_iron_*/'}, '#forge:plates/iron', '#forge:plates/industrial_iron')
  IRRebirth.replaceInput({output: '/steampowered:cast_iron_*/'}, '#forge:ingots/iron', '#forge:ingots/industrial_iron')
  IRRebirth.replaceInput({output: 'steampowered:alternator'}, '#forge:ingots/iron', 'createaddition:capacitor')
  IRRebirth.replaceInput({output: 'steampowered:alternator'}, '#forge:plates/copper', '#forge:plates/brass')
  IRRebirth.replaceInput({output: '/steampowered:.*/'}, 'minecraft:bricks', 'immersiveengineering:cokebrick')
})