ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ output: 'create:brass_casing'})
    IRRebirth.remove({ output: '#create:sandpaper'})
    IRRebirth.remove({ output: 'create:copper_casing'})
    IRRebirth.remove({ id: 'create:crafting/kinetics/empty_blaze_burner'})
    IRRebirth.remove({ output: ['createaddition:large_connector', 'createaddition:connector', 'createaddition:festive_spool', 'createaddition:spool', 'createaddition:copper_spool', 'createaddition:gold_spool', 'createaddition:electrum_spool', 'createaddition:gold_wire', 'create_sa:andesite_jetpack_chestplate', 'create_sa:copper_jetpack_chestplate', 'create_sa:brass_jetpack_chestplate', 'create_sa:andesite_exoskeleton_chestplate', 'create_sa:copper_exoskeleton_chestplate', 'create_sa:brass_exoskeleton_chestplate']})
    IRRebirth.remove({ id: 'create:crafting/kinetics/white_sail' })
    IRRebirth.remove({ output: 'create:brass_ingot', type: 'create:mixing'})
    IRRebirth.remove({ output: 'immersiveengineering:ingot_electrum', type: 'create:mixing'})
    IRRebirth.remove({ output: 'immersiveengineering:ingot_constantan', type: 'create:mixing'})
    IRRebirth.remove({id: 'create_deep_dark:mixing_molten_echo_compat'})
})