ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ output: 'create:brass_casing'})
    IRRebirth.remove({ output: '#create:sandpaper'})
    IRRebirth.remove({ output: 'create:copper_casing'})
    IRRebirth.remove({ id: 'create:crafting/kinetics/empty_blaze_burner'})
    IRRebirth.remove({ output: ['create_sa:andesite_jetpack_chestplate', 'create_sa:copper_jetpack_chestplate', 'create_sa:brass_jetpack_chestplate', 'create_sa:andesite_exoskeleton_chestplate', 'create_sa:copper_exoskeleton_chestplate', 'create_sa:brass_exoskeleton_chestplate']})
    IRRebirth.remove({ id: 'create:crafting/kinetics/white_sail' })
    IRRebirth.remove({ output: 'create:brass_ingot', type: 'create:mixing'})
    IRRebirth.remove({ output: 'immersiveengineering:ingot_electrum', type: 'create:mixing'})
    IRRebirth.remove({ output: 'immersiveengineering:ingot_constantan', type: 'create:mixing'})
    IRRebirth.remove({id: 'create_deep_dark:mixing_molten_echo_compat'})
    IRRebirth.remove({id: 'create:crafting/materials/andesite_alloy'})
    IRRebirth.remove({id: 'create:mixing/andesite_alloy'})
    IRRebirth.remove({ output: 'create:railway_casing'})
    IRRebirth.remove({ output: 'create_dd:bronze_block'})
    IRRebirth.remove({ output: 'create_dd:bronze_sheet'})
    IRRebirth.remove({ output: 'create_dd:bronze_nugget'})
    IRRebirth.remove({ output: 'create_dd:bronze_ingot'})
    IRRebirth.remove({id: 'createdeco:industrial_iron_ingot_from_industrial_iron_block'})
    IRRebirth.remove({id: 'create_dd:compacting/steel'})
    IRRebirth.remove({output: 'createdeco:industrial_iron_ingot'})
    IRRebirth.remove({output: 'create_dd:andesite_sheet'})
    IRRebirth.remove({output: 'create_dd:flywheel'})
    IRRebirth.remove({output: 'create_dd:furnace_engine'})
    IRRebirth.remove({output: 'createadditions:alternator'})
    IRRebirth.remove({id: '/create_dd:emptying/sap_from_.*/'})
    IRRebirth.remove({id: 'createdeco:industrial_iron_nugget_from_industrial_iron_ingot'})
    IRRebirth.remove({id: '/createaddition:compat/tconstruct/.*/'})
    IRRebirth.remove({id: '/tconstruct:compat/create/andesite_alloy_.*/'})
    IRRebirth.remove({id: 'create_mechanical_chicken:compacting/compacting_seed_oil'})
    IRRebirth.remove({id: 'create:industrial_iron_block_from_ingots_iron_stonecutting'})
    IRRebirth.remove({id: 'create_dd:compacting/steel_ingot'})
})