ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.create.deploying('immersiveengineering:alloybrick', ['#forge:sandstone', 'minecraft:brick'])
    IRRebirth.recipes.create.deploying('create:brass_casing', ['#forge:treated_wood', '#forge:plates/brass'])
    IRRebirth.recipes.create.deploying('create:copper_casing', ['#forge:stripped_logs', '#forge:plates/copper'])
    IRRebirth.recipes.create.deploying('create:copper_casing', ['#forge:stripped_wood', '#forge:plates/copper'])
    IRRebirth.recipes.create.deploying('createaddition:diamond_grit_sandpaper', ['create:sand_paper', '#forge:dusts/diamond'])
    IRRebirth.recipes.create.deploying('createaddition:diamond_grit_sandpaper', ['create:red_sand_paper', '#forge:dusts/diamond'])
    IRRebirth.recipes.create.deploying('immersiveengineering:blastbrick_reinforced', ['immersiveengineering:blastbrick', '#forge:plates/steel'])
    IRRebirth.recipes.create.deploying('kubejs:nether_frame_bricks', ['minecraft:sculk', '#forge:plates/brass'])
    IRRebirth.recipes.create.deploying('kubejs:mining_frame_bricks', ['immersiveengineering:insulating_glass', '#forge:plates/lead'])
    IRRebirth.recipes.create.deploying('kubejs:end_frame_bricks', ['minecraft:end_stone_bricks', 'minecraft:dragon_breath'])
    IRRebirth.recipes.create.deploying('kubejs:end_mining_frame_bricks', ['minecraft:end_stone_bricks', '#forge:ingots/draconium'])
    IRRebirth.recipes.create.deploying('kubejs:nether_mining_frame_bricks', ['#forge:storage_blocks/refined_obsidian', '#forge:plates/netherite'])
    IRRebirth.recipes.create.deploying('kubejs:void_frame_bricks', ['ae2:fluix_block', '#forge:plates/certus'])
    IRRebirth.recipes.create.deploying('create:railway_casing', ['create:brass_casing', 'create:sturdy_sheet'])
    IRRebirth.recipes.create.deploying('create:rose_quartz', ['biomesoplenty:rose_quartz_block', '#create:sandpaper'])
})