ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.create.mixing([Fluid.of('immersiveengineering:creosote', 250)], [Fluid.water(250), '#minecraft:logs'])
    IRRebirth.recipes.create.mixing(['immersiveengineering:dust_nickel', Item.of('immersiveengineering:dust_nickel').withChance(0.25)], [Fluid.water(100),'jaopca:mekanism_dirty_dusts.nickel'])
    IRRebirth.recipes.create.mixing(['immersiveengineering:dust_silver', Item.of('immersiveengineering:dust_silver').withChance(0.25)], [Fluid.water(100), 'jaopca:mekanism_dirty_dusts.silver'])
    IRRebirth.recipes.create.mixing(['immersiveengineering:dust_aluminum', Item.of('immersiveengineering:dust_aluminum').withChance(0.25)], [Fluid.water(100), 'jaopca:mekanism_dirty_dusts.aluminum'])
    IRRebirth.recipes.create.mixing(['mekanism:dust_uranium', Item.of('mekanism:dust_uranium').withChance(0.25)], [Fluid.water(100), 'mekanism:dirty_dust_uranium'])
    IRRebirth.recipes.create.mixing(['mekanism:dust_lead', Item.of('mekanism:dust_lead').withChance(0.25)], [Fluid.water(100), 'mekanism:dirty_dust_lead'])
    IRRebirth.recipes.create.mixing(['mekanism:dust_tin', Item.of('mekanism:dust_tin').withChance(0.25)], [Fluid.water(100), 'mekanism:dirty_dust_tin'])
    IRRebirth.recipes.create.mixing(['mekanism:dust_osmium', Item.of('mekanism:dust_osmium').withChance(0.25)], [Fluid.water(100), 'mekanism:dirty_dust_osmium'])
    IRRebirth.recipes.create.mixing(['mekanism:dust_gold', Item.of('mekanism:dust_gold').withChance(0.25)], [Fluid.water(100), 'mekanism:dirty_dust_gold'])
    IRRebirth.recipes.create.mixing(['mekanism:dust_copper', Item.of('mekanism:dust_copper').withChance(0.25)], [Fluid.water(100), 'mekanism:dirty_dust_copper'])
    IRRebirth.recipes.create.mixing(['mekanism:dust_iron', Item.of('mekanism:dust_iron').withChance(0.25)], [Fluid.water(100), 'mekanism:dirty_dust_iron'])
    IRRebirth.recipes.create.mixing(['jaopca:dusts.zinc', Item.of('jaopca:dusts.zinc').withChance(0.25)], [Fluid.water(100), 'jaopca:mekanism_dirty_dusts.zinc'])
    IRRebirth.recipes.create.mixing(['create:brass_nugget', Item.of('create:brass_nugget').withChance(0.50)], [Fluid.lava(100),'#forge:ingots/copper', '#forge:ingots/zinc'])
    IRRebirth.recipes.create.mixing(['mekanism:nugget_steel', Item.of('mekanism:nugget_steel').withChance(0.50)], [Fluid.lava(100),'#forge:ingots/iron', '#minecraft:coals'])
    IRRebirth.recipes.create.mixing('minecraft:obsidian', [Fluid.water(1000), Fluid.lava(1000)])
    IRRebirth.recipes.create.mixing('immersiveengineering:dust_coke', [Item.of('#forge:dusts/coal', 4), Fluid.of("immersiveengineering:creosote", 1000)]).heated()
    IRRebirth.recipes.create.mixing('kubejs:raw_blast_brick', [Item.of('create:cinder_flour', 4), 'minecraft:clay', Fluid.water(100)]).heated()
    IRRebirth.recipes.create.mixing([Fluid.of('immersiveengineering:redstone_acid', 250)], [Fluid.water(250), '#forge:dusts/redstone'])
  })