ServerEvents.recipes(IRRebirth => {
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:sand/colorless"},"result": {"item": "create:sand_paper","count": 1}})
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:sand/red"},"result": {"item": "create:red_sand_paper","count": 1}})
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:ingots/iron"},"result": {"item": "immersiveengineering:stick_iron","count": 1}}).id('createaddition:rolling/iron_ingot')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:ingots/steel"},"result": {"item": "immersiveengineering:stick_steel","count": 1}}).id('createaddition:rolling/steel_ingot')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:ingots/aluminum"},"result": {"item": "immersiveengineering:stick_aluminum","count": 1}}).id('createaddition:rolling/aluminum_ingot')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:ingots/copper"},"result": {"item": "createaddition:copper_rod","count": 1}}).id('createaddition:rolling/copper_ingot')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:ingots/gold"},"result": {"item": "createaddition:gold_rod","count": 1}}).id('createaddition:rolling/gold_ingot')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:ingots/electrum"},"result": {"item": "createaddition:electrum_rod","count": 1}}).id('createaddition:rolling/electrum_ingot')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:ingots/brass"},"result": {"item": "createaddition:brass_rod","count": 1}}).id('createaddition:rolling/brass_ingot')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/copper"},"result": {"item": "immersiveengineering:wire_copper","count": 1}}).id('createaddition:rolling/copper_plate')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/electrum"},"result": {"item": "immersiveengineering:wire_electrum","count": 1}}).id('createaddition:rolling/electrum_plate')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/aluminum"},"result": {"item": "immersiveengineering:wire_aluminum","count": 1}}).id('createaddition:rolling/aluminum_plate')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/lead"},"result": {"item": "immersiveengineering:wire_lead","count": 1}}).id('createaddition:rolling/lead_plate')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/steel"},"result": {"item": "immersiveengineering:wire_steel","count": 1}}).id('createaddition:rolling/steel_plate')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"item": "immersiveengineering:wirecoil_structure_rope"},"result": {"item": "immersiveengineering:hemp_fabric","count": 1}})
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/iron"},"result": {"item": "createaddition:iron_wire","count": 1}}).id('createaddition:rolling/iron_plate')
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/osmium"},"result": {"item": "kubejs:osmium_rod","count": 1}})
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/bronze"},"result": {"item": "kubejs:bronze_rod","count": 1}})
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/refined_glowstone"},"result": {"item": "kubejs:refined_glowstone_rod","count": 1}})
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:plates/refined_obsidian"},"result": {"item": "kubejs:refined_obsidian_rod","count": 1}})
  IRRebirth.custom({"type":"createaddition:rolling","input": {"tag": "forge:gems/diamond"},"result": {"item": "kubejs:diamond_rod","count": 1}})
})