ServerEvents.tags("block", (IRRebirth) => {
  IRRebirth.add("minecraft:crops", "agricraft:crop");

  let buddingCrystals = [
    "buddingcrystals:budding_fluix",
    "buddingcrystals:budding_certus_quartz",
    "buddingcrystals:budding_nether_quartz",
    "buddingcrystals:budding_glowstone",
    "buddingcrystals:budding_prismarine",
    "buddingcrystals:budding_steel",
    "buddingcrystals:budding_refined_obsidian",
    "buddingcrystals:budding_spirited_crystal",
    "buddingcrystals:budding_aluminum",
    "buddingcrystals:budding_niotic_crystal",
    "buddingcrystals:budding_netherite",
    "buddingcrystals:budding_gold",
    "buddingcrystals:budding_nitro_crystal",
    "buddingcrystals:budding_lapis_lazuli",
    "buddingcrystals:budding_tin",
    "buddingcrystals:budding_fluorite",
    "buddingcrystals:budding_copper",
    "buddingcrystals:budding_refined_glowstone",
    "buddingcrystals:budding_awakened_draconium",
    "buddingcrystals:budding_blazing_crystal",
    "buddingcrystals:budding_zinc",
    "buddingcrystals:budding_electrum",
    "buddingcrystals:budding_nickel",
    "buddingcrystals:budding_salt",
    "buddingcrystals:budding_hop_graphite",
    "buddingcrystals:budding_energized_steel",
    "buddingcrystals:budding_osmium",
    "buddingcrystals:budding_brass",
    "buddingcrystals:budding_constantan",
    "buddingcrystals:budding_lead",
    "buddingcrystals:budding_bronze",
    "buddingcrystals:budding_draconium",
    "buddingcrystals:budding_diamond",
    "buddingcrystals:budding_uraninite",
    "buddingcrystals:budding_coal",
    "buddingcrystals:budding_iron",
    "buddingcrystals:budding_silver",
    "buddingcrystals:budding_uranium",
    "buddingcrystals:budding_redstone",
    "buddingcrystals:budding_emerald",
    "buddingcrystals:budding_quantum_alloy",
    "buddingcrystals:budding_skeleton",
    "buddingcrystals:budding_creeper",
    "buddingcrystals:budding_zombie",
    "buddingcrystals:budding_sheep",
    "buddingcrystals:budding_spider",
    "buddingcrystals:budding_bee",
    "buddingcrystals:budding_snow_golem",
    "buddingcrystals:budding_skysteel",
    "buddingcrystals:budding_squid",
    "buddingcrystals:budding_glow_squid",
    "buddingcrystals:budding_blaze",
    "buddingcrystals:budding_wither_skeleton",
    "buddingcrystals:budding_ghast",
    "buddingcrystals:budding_enderman",
    "buddingcrystals:budding_sculk",
    "buddingcrystals:budding_cow",
    "buddingcrystals:budding_acidicredstone",
    "buddingcrystals:budding_magma_cube",
    "buddingcrystals:budding_chicken",
    "buddingcrystals:budding_phantom",
    "buddingcrystals:budding_flint",
    "buddingcrystals:budding_slime",
    "buddingcrystals:budding_wither",
    "buddingcrystals:budding_chaos_dragon",
    "buddingcrystals:budding_coalcoke",
  ];

  buddingCrystals.forEach((crystal) => {
    IRRebirth.add("forge:budding", crystal);
  });
});
