ServerEvents.tags("block", (IRRebirth) => {
  IRRebirth.add("minecraft:crops", "agricraft:crop");

  let buddingCrystals = [
    "buddingcrystals:budding_fluix",
    "buddingcrystals:budding_certus_quartz",
    "buddingcrystals:budding_nether_quartz",
    "buddingcrystals:budding_glowstone",
    "buddingcrystals:budding_prismarine",
    "buddingcrystals:budding_steel",
    "buddingcrystals:budding_refinedobsidian",
    "buddingcrystals:budding_spiritedcrystal",
    "buddingcrystals:budding_aluminum",
    "buddingcrystals:budding_nioticcrystal",
    "buddingcrystals:budding_netherite",
    "buddingcrystals:budding_gold",
    "buddingcrystals:budding_nitrocrystal",
    "buddingcrystals:budding_lapis_lazuli",
    "buddingcrystals:budding_tin",
    "buddingcrystals:budding_fluorite",
    "buddingcrystals:budding_copper",
    "buddingcrystals:budding_refinedglowstone",
    "buddingcrystals:budding_awakeneddraconium",
    "buddingcrystals:budding_blazingcrystal",
    "buddingcrystals:budding_zinc",
    "buddingcrystals:budding_electrum",
    "buddingcrystals:budding_nickel",
    "buddingcrystals:budding_salt",
    "buddingcrystals:budding_hopgraphite",
    "buddingcrystals:budding_energizedsteel",
    "buddingcrystals:budding_osmium",
    "buddingcrystals:budding_brass",
    "buddingcrystals:budding_constantan",
    "buddingcrystals:budding_lead",
    "buddingcrystals:budding_bronze",
    "buddingcrystals:budding_draconium",
    "buddingcrystals:budding_diamond",
    "buddingcrystals:budding_uraninite",
    "buddingcrystals:budding_coal",
    "buddingcrystals:budding_iron",
    "buddingcrystals:budding_silver",
    "buddingcrystals:budding_uranium",
    "buddingcrystals:budding_redstone",
    "buddingcrystals:budding_emerald",
    "buddingcrystals:budding_quantumalloy",
    "buddingcrystals:budding_skeleton",
    "buddingcrystals:budding_creeper",
    "buddingcrystals:budding_zombie",
    "buddingcrystals:budding_sheep",
    "buddingcrystals:budding_spider",
    "buddingcrystals:budding_bee",
    "buddingcrystals:budding_snowgolem",
    "buddingcrystals:budding_skysteel",
    "buddingcrystals:budding_squid",
    "buddingcrystals:budding_glowsquid",
    "buddingcrystals:budding_blaze",
    "buddingcrystals:budding_witherskeleton",
    "buddingcrystals:budding_ghast",
    "buddingcrystals:budding_enderman",
    "buddingcrystals:budding_sculk",
    "buddingcrystals:budding_cow",
    "buddingcrystals:budding_acidicredstone",
    "buddingcrystals:budding_magmacube",
    "buddingcrystals:budding_chicken",
    "buddingcrystals:budding_phantom",
    "buddingcrystals:budding_flint",
    "buddingcrystals:budding_slime",
    "buddingcrystals:budding_wither",
    "buddingcrystals:budding_chaosdragon",
    "buddingcrystals:budding_coalcoke",
  ];

  buddingCrystals.forEach((crystal) => {
    IRRebirth.add("forge:budding", crystal);
  });
});
