StartupEvents.registry('fluid', IRRebirth => {
    IRRebirth.create('skeleton_exp')
        .displayName('Skeleton Experience Essence')
        .thinTexture(0xF1F6CC)
        .bucketColor(0xF1F6CC)
        .tag('forge:experience/skeleton')
    IRRebirth.create('creeper_exp')
        .displayName('Creeper Experience Essence')
        .thinTexture(0x80967E)
        .bucketColor(0x80967E)
        .tag('forge:experience/creeper')
    IRRebirth.create('zombie_exp')
        .displayName('Zombie Experience Essence')
        .thinTexture(0x55A757)
        .bucketColor(0x55A757)
        .tag('forge:experience/zombie')
    IRRebirth.create('blaze_exp')
        .displayName('Blaze Experience Essence')
        .thinTexture(0xCA8515)
        .bucketColor(0xCA8515)
        .tag('forge:experience/blaze')
    IRRebirth.create('wither_skeleton_exp')
        .displayName('Wither Skeleton Experience Essence')
        .thinTexture(0x525252)
        .bucketColor(0x525252)
        .tag('forge:experience/wither_skeleton')
    IRRebirth.create('ghast_exp')
        .displayName('Ghast Experience Essence')
        .thinTexture(0xB4B4B4)
        .bucketColor(0xB4B4B4)
        .tag('forge:experience/ghast')
    IRRebirth.create('enderman_exp')
        .displayName('Enderman Experience Essence')
        .thinTexture(0x35604D)
        .bucketColor(0x35604D)
        .tag('forge:experience/enderman')
    IRRebirth.create('sculk_exp')
        .displayName('Sculk Experience Essence')
        .thinTexture(0x3D3560)
        .bucketColor(0x3D3560)
        .tag('forge:experience/sculk')
    IRRebirth.create('cow_exp')
        .displayName('Cow Experience Essence')
        .thinTexture(0xBD710B)
        .bucketColor(0xBD710B)
        .tag('forge:experience/cow')
    IRRebirth.create('sheep_exp')
        .displayName('Sheep Experience Essence')
        .thinTexture(0xEEEEEE)
        .bucketColor(0xEEEEEE)
        .tag('forge:experience/sheep')
    IRRebirth.create('spider_exp')
        .displayName('Spider Experience Essence')
        .thinTexture(0x612828)
        .bucketColor(0x612828)
        .tag('forge:experience/spider')
    IRRebirth.create('bee_exp')
        .displayName('Bee Experience Essence')
        .thinTexture(0xC9AC3D)
        .bucketColor(0xC9AC3D)
        .tag('forge:experience/bee')
    IRRebirth.create('snow_golem_exp')
        .displayName('Snow Golem Experience Essence')
        .thinTexture(0xD9A257)
        .bucketColor(0xD9A257)
        .tag('forge:experience/snow_golem')
    IRRebirth.create('squid_exp')
        .displayName('Squid Experience Essence')
        .thinTexture(0x202020)
        .bucketColor(0x202020)
        .tag('forge:experience/squid')
    IRRebirth.create('glow_squid_exp')
        .displayName('Glow Squid Experience Essence')
        .thinTexture(0x399A8D)
        .bucketColor(0x399A8D)
        .tag('forge:experience/glow_squid')
    IRRebirth.create('slime_exp')
        .displayName('Slime Experience Essence')
        .thinTexture(0x83EC94)
        .bucketColor(0x83EC94)
        .tag('forge:experience/slime')
    IRRebirth.create('wither_exp')
        .displayName('Wither Experience Essence')
        .thinTexture(0x646965)
        .bucketColor(0x646965)
        .tag('forge:experience/wither')
    IRRebirth.create('magma_cube_exp')
        .displayName('Magma Cube Experience Essence')
        .thinTexture(0xC97516)
        .bucketColor(0xC97516)
        .tag('forge:experience/magma_cube')
    IRRebirth.create('phantom_exp')
        .displayName('Phantom Experience Essence')
        .thinTexture(0x4A4E89)
        .bucketColor(0x4A4E89)
        .tag('forge:experience/phantom')
    IRRebirth.create('chicken_exp')
        .displayName('Chicken Experience Essence')
        .thinTexture(0xB09C7D)
        .bucketColor(0xB09C7D)
        .tag('forge:experience/chicken')
})