StartupEvents.registry('item', IRRebirth => {
    IRRebirth.create('blaze_clay')
        .displayName('Blazing Clay')
        .tooltip('Clay with a Firey Like Color')
    IRRebirth.create('fluix_wire')
        .displayName('Fluix Wire')
        .tag('forge:wires')
        .tag('forge:wires/fluix')
        .tag('immersiveengineering:circuits/solder')
    IRRebirth.create('certus_wire')
        .displayName('Certus Wire')
        .tag('forge:wires')
        .tag('forge:wires/certus')
        .tag('immersiveengineering:circuits/solder')
    IRRebirth.create('fluix_plate')
        .displayName('Fluix Plate')
        .tag('forge:plates')
        .tag('forge:plates/fluix')
    IRRebirth.create('certus_plate')
        .displayName('Certus Plate')
        .tag('forge:plates')
        .tag('forge:plates/certus')
    IRRebirth.create('andesite_plate')
        .displayName('Andesite Alloy Plate')
        .tag('forge:plates')
        .tag('forge:plates/andesite_alloy')
    IRRebirth.create('osmium_plate')
        .displayName('Osmium Plate')
        .tag('forge:plates')
        .tag('forge:plates/osmium')
    IRRebirth.create('osmium_rod')
        .displayName('Osmium Rod')
        .tag('forge:rods/all_metal')
        .tag('forge:rods/osmium')
    IRRebirth.create('bronze_plate')
        .displayName('Bronze Plate')
        .tag('forge:plates')
        .tag('forge:plates/bronze')
    IRRebirth.create('bronze_rod')
        .displayName('Bronze Rod')
        .tag('forge:rods/all_metal')
        .tag('forge:rods/bronze')
    IRRebirth.create('refined_glowstone_plate')
        .displayName('Refined Glowstone Plate')
        .tag('forge:plates')
        .tag('forge:plates/refined_glowstone')
    IRRebirth.create('refined_glowstone_rod')
        .displayName('Refined Glowstone Rod')
        .tag('forge:rods/all_metal')
        .tag('forge:rods/refined_glowstone')
    IRRebirth.create('refined_obsidian_plate')
        .displayName('Refined Obsidian Plate')
        .tag('forge:plates')
        .tag('forge:plates/refined_obsidian')
    IRRebirth.create('refined_obsidian_rod')
        .displayName('Refined Obsidian Rod')
        .tag('forge:rods/all_metal')
        .tag('forge:rods/refined_obsidian')
    IRRebirth.create('tin_plate')
        .displayName('Tin Plate')
        .tag('forge:plates')
        .tag('forge:plates/tin')
    IRRebirth.create('tin_rod')
        .displayName('Tin Rod')
        .tag('forge:rods/all_metal')
        .tag('forge:rods/tin')
    IRRebirth.create('graphite_plate')
        .displayName('HOP Graphite Plate')
        .tag('forge:plates')
        .tag('forge:plates/hop_graphite')
    IRRebirth.create('acidic_redstone')
        .displayName('Acidic Redstone Dust')
        .tag('forge:dusts')
        .tooltip('Potent Redstone')
    IRRebirth.create('dust_mold')
        .displayName('Metal Press Mold: Dust')
})