StartupEvents.registry('item', IRRebirth => {
    IRRebirth.create('graphite_mesh','createsifter:advanced_mesh')
        .displayName('Hempen Graphite Mesh')
        .parentModel("createsifter:block/meshes/mesh")
        .texture("mesh","kubejs:item/hemp_mesh")
        .texture("frame", "kubejs:item/graphite_frame")
    IRRebirth.create('obsidian_mesh','createsifter:advanced_mesh')
        .displayName('Refined Obsidian Mesh')
        .parentModel("createsifter:block/meshes/mesh")
        .texture("mesh","kubejs:item/refined_obsidian_mesh")
        .texture("frame", "kubejs:item/hdpe_frame")
    IRRebirth.create('awakened_mesh','createsifter:advanced_mesh')
        .displayName('Awakened Mesh')
        .parentModel("createsifter:block/meshes/mesh")
        .texture("mesh","kubejs:item/awakened_mesh")
        .texture("frame", "kubejs:item/wyvern_frame")
})