ClientEvents.highPriorityAssets(IRRebirth => {
    IRRebirth.addLang('gas.kubejs.oxidized_aluminum', "Oxidized Aluminum")
    IRRebirth.addLang('gas.kubejs.oxidized_refined_obsidian', "Oxidized Refined Obsidian")
    IRRebirth.addLang('gas.kubejs.oxidized_certus_quartz', "Oxidized Certus Quartz")
    IRRebirth.addLang('gas.kubejs.oxidized_steel', "Oxidized Steel")
    IRRebirth.addLang('gas.kubejs.oxidized_prismarine', "Oxidized Prismarine")
    IRRebirth.addLang('gas.kubejs.oxidized_lapis', "Oxidized Lapis")
    IRRebirth.addLang('gas.kubejs.oxidized_gold', "Oxidized Gold")
    IRRebirth.addLang('gas.kubejs.oxidized_netherite', "Oxidized Netherite")
    IRRebirth.addLang('gas.kubejs.oxidized_fluix', "Oxidized Fluix")
    IRRebirth.addLang('gas.kubejs.oxidized_glowstone', "Oxidized Glowstone")
    IRRebirth.addLang('gas.kubejs.oxidized_uraninite', "Oxidized Uraninite")
    IRRebirth.addLang('gas.kubejs.oxidized_iron', "Oxidized Iron")
    IRRebirth.addLang('gas.kubejs.oxidized_silver', "Oxidized Silver")
    IRRebirth.addLang('gas.kubejs.oxidized_uranium', "Oxidized Uranium")
    IRRebirth.addLang('gas.kubejs.oxidized_redstone', "Oxidized Redstone")
    IRRebirth.addLang('gas.kubejs.oxidized_emerald', "Oxidized Emerald")
    IRRebirth.addLang('gas.kubejs.oxidized_nether_quartz', "Oxidized Nether Quartz")
    IRRebirth.addLang('gas.kubejs.oxidized_nickel', "Oxidized Nickel")
    IRRebirth.addLang('gas.kubejs.oxidized_electrum', "Oxidized Electrum")
    IRRebirth.addLang('gas.kubejs.oxidized_bronze', "Oxidized Bronze")
    IRRebirth.addLang('gas.kubejs.oxidized_draconium', "Oxidized Draconium")
    IRRebirth.addLang('gas.kubejs.oxidized_diamond', "Oxidized Diamond")
    IRRebirth.addLang('gas.kubejs.oxidized_lead', "Oxidized Lead")
    IRRebirth.addLang('gas.kubejs.oxidized_constantan', "Oxidized Constantan")
    IRRebirth.addLang('gas.kubejs.oxidized_brass', "Oxidized Brass")
    IRRebirth.addLang('gas.kubejs.oxidized_graphite', "Oxidized Graphite")
    IRRebirth.addLang('gas.kubejs.oxidized_tin', "Oxidized Tin")
    IRRebirth.addLang('gas.kubejs.oxidized_zinc', "Oxidized Zinc")
    IRRebirth.addLang('gas.kubejs.oxidized_awakened_draconium', "Oxidized Awakened Draconium")
    IRRebirth.addLang('gas.kubejs.oxidized_refined_glowstone', "Oxidized Refined Glowstone")
    IRRebirth.addLang('gas.kubejs.oxidized_copper', "Oxidized Copper")
    IRRebirth.addLang('gas.kubejs.oxidized_energized_steel', "Oxidized Energized Steel")
    IRRebirth.addLang('gas.kubejs.oxidized_blazing', "Oxidized Blazing Crystal")
    IRRebirth.addLang('gas.kubejs.oxidized_niotic', "Oxidized Niotic Crystal")
    IRRebirth.addLang('gas.kubejs.oxidized_spirited', "Oxidized Spirited Crystal")
    IRRebirth.addLang('gas.kubejs.oxidized_nitro', "Oxidized Nitro Crystal")
    IRRebirth.addLang('gas.kubejs.oxidized_carbon', "Oxidized Carbon")
    IRRebirth.addLang('gas.kubejs.oxidized_fluorite', "Oxidized Fluorite")
    IRRebirth.addLang('gas.kubejs.oxidized_amethyst', "Oxidized Amethyst")
    IRRebirth.addLang('gas.kubejs.oxidized_sky_steel', "Oxidized Sky Steel")
    IRRebirth.addLang('gas.kubejs.oxidized_quantum_alloy', "Oxidized Quantum Alloy")
    IRRebirth.addLang('gas.kubejs.oxidized_osmium', "Oxidized Osmium")
    IRRebirth.addLang('gas.kubejs.irradiated_aluminum', "Irradiated Aluminum")
    IRRebirth.addLang('gas.kubejs.irradiated_refined_obsidian', "Irradiated Refined Obsidian")
    IRRebirth.addLang('gas.kubejs.irradiated_certus_quartz', "Irradiated Certus Quartz")
    IRRebirth.addLang('gas.kubejs.irradiated_steel', "Irradiated Steel")
    IRRebirth.addLang('gas.kubejs.irradiated_prismarine', "Irradiated Prismarine")
    IRRebirth.addLang('gas.kubejs.irradiated_lapis', "Irradiated Lapis")
    IRRebirth.addLang('gas.kubejs.irradiated_gold', "Irradiated Gold")
    IRRebirth.addLang('gas.kubejs.irradiated_netherite', "Irradiated Netherite")
    IRRebirth.addLang('gas.kubejs.irradiated_fluix', "Irradiated Fluix")
    IRRebirth.addLang('gas.kubejs.irradiated_glowstone', "Irradiated Glowstone")
    IRRebirth.addLang('gas.kubejs.irradiated_uraninite', "Irradiated Uraninite")
    IRRebirth.addLang('gas.kubejs.irradiated_iron', "Irradiated Iron")
    IRRebirth.addLang('gas.kubejs.irradiated_silver', "Irradiated Silver")
    IRRebirth.addLang('gas.kubejs.irradiated_uranium', "Irradiated Uranium")
    IRRebirth.addLang('gas.kubejs.irradiated_redstone', "Irradiated Redstone")
    IRRebirth.addLang('gas.kubejs.irradiated_emerald', "Irradiated Emerald")
    IRRebirth.addLang('gas.kubejs.irradiated_nether_quartz', "Irradiated Nether Quartz")
    IRRebirth.addLang('gas.kubejs.irradiated_nickel', "Irradiated Nickel")
    IRRebirth.addLang('gas.kubejs.irradiated_electrum', "Irradiated Electrum")
    IRRebirth.addLang('gas.kubejs.irradiated_bronze', "Irradiated Bronze")
    IRRebirth.addLang('gas.kubejs.irradiated_draconium', "Irradiated Draconium")
    IRRebirth.addLang('gas.kubejs.irradiated_diamond', "Irradiated Diamond")
    IRRebirth.addLang('gas.kubejs.irradiated_lead', "Irradiated Lead")
    IRRebirth.addLang('gas.kubejs.irradiated_constantan', "Irradiated Constantan")
    IRRebirth.addLang('gas.kubejs.irradiated_brass', "Irradiated Brass")
    IRRebirth.addLang('gas.kubejs.irradiated_graphite', "Irradiated Graphite")
    IRRebirth.addLang('gas.kubejs.irradiated_tin', "Irradiated Tin")
    IRRebirth.addLang('gas.kubejs.irradiated_zinc', "Irradiated Zinc")
    IRRebirth.addLang('gas.kubejs.irradiated_awakened_draconium', "Irradiated Awakened Draconium")
    IRRebirth.addLang('gas.kubejs.irradiated_refined_glowstone', "Irradiated Refined Glowstone")
    IRRebirth.addLang('gas.kubejs.irradiated_copper', "Irradiated Copper")
    IRRebirth.addLang('gas.kubejs.irradiated_energized_steel', "Irradiated Energized Steel")
    IRRebirth.addLang('gas.kubejs.irradiated_blazing', "Irradiated Blazing Crystal")
    IRRebirth.addLang('gas.kubejs.irradiated_niotic', "Irradiated Niotic Crystal")
    IRRebirth.addLang('gas.kubejs.irradiated_spirited', "Irradiated Spirited Crystal")
    IRRebirth.addLang('gas.kubejs.irradiated_nitro', "Irradiated Nitro Crystal")
    IRRebirth.addLang('gas.kubejs.irradiated_carbon', "Irradiated Carbon")
    IRRebirth.addLang('gas.kubejs.irradiated_fluorite', "Irradiated Fluorite")
    IRRebirth.addLang('gas.kubejs.irradiated_amethyst', "Irradiated Amethyst")
    IRRebirth.addLang('gas.kubejs.irradiated_sky_steel', "Irradiated Sky Steel")
    IRRebirth.addLang('gas.kubejs.irradiated_quantum_alloy', "Irradiated Quantum Alloy")
    IRRebirth.addLang('gas.kubejs.irradiated_acidic_redstone', "Irradiated Acidic Redstone")
    IRRebirth.addLang('gas.kubejs.irradiated_osmium', "Irradiated Osmium")
})