ClientEvents.highPriorityAssets(IRRebirth => {
    IRRebirth.addLang('gas.kubejs.aluminum_gas', "Aluminum Gas")
    IRRebirth.addLang('gas.kubejs.refined_obsidian_gas', "Refined Obsidian Gas")
    IRRebirth.addLang('gas.kubejs.certus_quartz_gas', "Certus Quartz Gas")
    IRRebirth.addLang('gas.kubejs.steel_gas', "Steel Gas")
    IRRebirth.addLang('gas.kubejs.prismarine_gas', "Prismarine Gas")
    IRRebirth.addLang('gas.kubejs.lapis_gas', "Lapis Gas")
    IRRebirth.addLang('gas.kubejs.gold_gas', "Gold Gas")
    IRRebirth.addLang('gas.kubejs.netherite_gas', "Netherite Gas")
    IRRebirth.addLang('gas.kubejs.fluix_gas', "Fluix Gas")
    IRRebirth.addLang('gas.kubejs.glowstone_gas', "Glowstone Gas")
    IRRebirth.addLang('gas.kubejs.uraninite_gas', "Uraninite Gas")
    IRRebirth.addLang('gas.kubejs.iron_gas', "Iron Gas")
    IRRebirth.addLang('gas.kubejs.silver_gas', "Silver Gas")
    IRRebirth.addLang('gas.kubejs.uranium_gas', "Uranium Gas")
    IRRebirth.addLang('gas.kubejs.redstone_gas', "Redstone Gas")
    IRRebirth.addLang('gas.kubejs.emerald_gas', "Emerald Gas")
    IRRebirth.addLang('gas.kubejs.nether_quartz_gas', "Nether Quartz Gas")
    IRRebirth.addLang('gas.kubejs.nickel_gas', "Nickel Gas")
    IRRebirth.addLang('gas.kubejs.electrum_gas', "Electrum Gas")
    IRRebirth.addLang('gas.kubejs.bronze_gas', "Bronze Gas")
    IRRebirth.addLang('gas.kubejs.draconium_gas', "Draconium Gas")
    IRRebirth.addLang('gas.kubejs.diamond_gas', "Diamond Gas")
    IRRebirth.addLang('gas.kubejs.lead_gas', "Lead Gas")
    IRRebirth.addLang('gas.kubejs.constantan_gas', "Constantan Gas")
    IRRebirth.addLang('gas.kubejs.brass_gas', "Brass Gas")
    IRRebirth.addLang('gas.kubejs.graphite_gas', "Graphite Gas")
    IRRebirth.addLang('gas.kubejs.tin_gas', "Tin Gas")
    IRRebirth.addLang('gas.kubejs.zinc_gas', "Zinc Gas")
    IRRebirth.addLang('gas.kubejs.awakened_draconium_gas', "Awakened Draconium Gas")
    IRRebirth.addLang('gas.kubejs.refined_glowstone_gas', "Refined Glowstone Gas")
    IRRebirth.addLang('gas.kubejs.copper_gas', "Copper Gas")
    IRRebirth.addLang('gas.kubejs.energized_steel_gas', "Energized Steel Gas")
    IRRebirth.addLang('gas.kubejs.blazing_gas', "Blazing Gas")
    IRRebirth.addLang('gas.kubejs.niotic_gas', "Niotic Gas")
    IRRebirth.addLang('gas.kubejs.spirited_gas', "Spirited Gas")
    IRRebirth.addLang('gas.kubejs.nitro_gas', "Nitro Gas")
    IRRebirth.addLang('gas.kubejs.carbon_gas', "Carbon Gas")
    IRRebirth.addLang('gas.kubejs.fluorite_gas', "Fluorite Gas")
    IRRebirth.addLang('gas.kubejs.amethyst_gas', "Amethyst Gas")
    IRRebirth.addLang('gas.kubejs.sky_steel_gas', "Sky Steel Gas")
    IRRebirth.addLang('gas.kubejs.quantum_alloy_gas', "Quantum Alloy Gas")
    IRRebirth.addLang('gas.kubejs.acidic_redstone_gas', "Acidic Redstone Gas")
    IRRebirth.addLang('gas.kubejs.flint_gas', "Flint Gas")

})