ServerEvents.recipes(IRRebirth => {
  IRRebirth.replaceInput({ output: 'powah:ender_cell_starter' },'minecraft:iron_nugget','#forge:ingots/silver')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_starter' },'minecraft:obsidian','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_basic' },'minecraft:iron_ingot','#forge:ingots/steel')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_basic' },'minecraft:obsidian','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_hardened' },'minecraft:obsidian','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_blazing' },'minecraft:obsidian','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_niotic' },'minecraft:obsidian','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_spirited' },'minecraft:obsidian','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:ender_cell_nitro' },'minecraft:obsidian','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:energy_cell_starter' },'minecraft:iron_ingot','#forge:ingots/steel')
  IRRebirth.replaceInput({ output: 'powah:energy_cell_basic' },'minecraft:iron_ingot','#forge:plates/steel')
  IRRebirth.replaceInput({ output: 'powah:thermoelectric_plate' },'minecraft:blaze_powder','kubejs:blaze_clay')
  IRRebirth.replaceInput({ output: 'powah:thermoelectric_plate' },'minecraft:redstone','kubejs:acidic_redstone')
  IRRebirth.replaceInput({ output: 'powah:thermo_generator_basic' },'minecraft:iron_ingot','#forge:plates/steel')
  IRRebirth.replaceInput({ output: 'powah:solar_panel_basic' },'minecraft:iron_ingot','#forge:plates/steel')
  IRRebirth.replaceInput({ output: 'powah:furnator_starter' },'minecraft:furnace','immersiveengineering:radiator')
  IRRebirth.replaceInput({ output: 'powah:furnator_basic' },'minecraft:iron_ingot','#forge:plates/steel')
  IRRebirth.replaceInput({ output: 'powah:furnator_starter' },'minecraft:bucket','immersiveengineering:fluid_pipe')
  IRRebirth.replaceInput({ output: 'powah:magmator_basic' },'minecraft:iron_ingot','#forge:plates/steel')
})