ServerEvents.recipes(IRRebirth => {
  IRRebirth.replaceInput({ output: 'powah:steel_energized' },'minecraft:iron_ingot','#forge:ingots/steel')
  IRRebirth.replaceInput({ output: 'powah:steel_energized' },'minecraft:gold_ingot','#forge:ingots/brass')
  IRRebirth.replaceInput({ output: 'powah:capacitor_basic' },'minecraft:iron_ingot','#forge:rods/refined_glowstone')
  IRRebirth.replaceInput({ output: 'powah:capacitor_basic' },'minecraft:redstone_block','mekanism:ultimate_control_circuit')
  IRRebirth.replaceInput({ output: 'powah:dielectric_casing' },'minecraft:iron_ingot','#forge:plates/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:wrench' },'minecraft:iron_ingot','#forge:rods/refined_obsidian')
  IRRebirth.replaceInput({ output: 'powah:crystal_nitro' },'minecraft:redstone_block','kubejs:acidic_redstone_block')
  IRRebirth.replaceInput({ output: 'powah:dielectric_rod' },'minecraft:iron_bars','mekanism:hdpe_rod')
  IRRebirth.replaceInput({ output: 'powah:dielectric_rod_horizontal' },'minecraft:iron_bars','mekanism:hdpe_rod')
  IRRebirth.replaceInput({ output: 'powah:energy_cable_starter' },'minecraft:iron_nugget','#forge:wires/iron')
  IRRebirth.replaceInput({ output: 'powah:photoelectric_pane' },'#c:glass_panes','mekanismgenerators:solar_panel')
  IRRebirth.replaceInput({ output: 'powah:photoelectric_pane' },'minecraft:lapis_lazuli','#forge:rods/electrum')
  IRRebirth.replaceInput({ output: 'powah:aerial_pearl' },'minecraft:iron_bars','mekanism:hdpe_rod')
  IRRebirth.replaceInput({ output: 'powah:aerial_pearl' },'minecraft:ender_pearl','ae2:fluix_pearl')
  IRRebirth.replaceInput({ output: 'powah:energizing_orb' },'#c:glass_blocks','mekanismgenerators:reactor_glass')
})