
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1171206
	#The name of the modpack
	modpackName = "The Immersive Revolution: Rebirth"
	#The version of the modpack
	modpackVersion = "0.12.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

