
[logbegone]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Couldn't set damage of loot item"]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Couldn't set damage of loot item"]

