ServerEvents.recipes((IRRebirth) => {
  
  let craftedItems = [
    'immersiveengineering:ingot_aluminum',
    'draconicevolution:awakened_draconium_nugget',
    'minecraft:honeycomb',
    'minecraft:blaze_rod',
    'powah:crystal_blazing',
    'create:brass_ingot',
    'mekanism:ingot_bronze',
    'ae2:certus_quartz_crystal',
    'draconicevolution:small_chaos_frag',
    'minecraft:chicken',
    'minecraft:coal',
    'immersiveengineering:ingot_constantan',
    'minecraft:copper_ingot',
    'minecraft:beef',
    'minecraft:gunpowder',
    'minecraft:diamond',
    'draconicevolution:draconium_ingot',
    'immersiveengineering:ingot_electrum',
    'minecraft:emerald',
    'minecraft:ender_pearl',
    'powah:steel_energized',
    'ae2:fluix_crystal',
    'mekanism:fluorite_gem',
    'minecraft:ghast_tear',
    'minecraft:glow_ink_sac',
    'minecraft:glowstone',
    'minecraft:gold_ingot',
    'immersiveengineering:ingot_hop_graphite',
    'minecraft:iron_ingot',
    'minecraft:lapis_lazuli',
    'mekanism:ingot_lead',
    'minecraft:magma_cream',
    'minecraft:quartz',
    'minecraft:netherite_ingot',
    'immersiveengineering:ingot_nickel',
    'powah:crystal_niotic',
    'powah:crystal_nitro',
    'mekanism:ingot_osmium',
    'minecraft:phantom_membrane',
    'minecraft:prismarine_crystals',
    'advanced_ae:quantum_alloy',
    'minecraft:redstone',
    'mekanism:ingot_refined_glowstone',
    'mekanism:ingot_refined_obsidian',
    'minecraft:echo_shard',
    'minecraft:mutton',
    'immersiveengineering:ingot_silver',
    'minecraft:bone',
    'megacells:sky_steel_ingot',
    'minecraft:slime_ball',
    'minecraft:snow',
    'minecraft:spider_eye',
    'powah:crystal_spirited',
    'minecraft:ink_sac',
    'mekanism:ingot_steel',
    'mekanism:ingot_tin',
    'powah:uraninite',
    'mekanism:ingot_uranium',
    'kubejs:nether_star_nugget',
    'minecraft:nether_star',
    'wstweaks:fragment',
    'create:zinc_ingot',
    'minecraft:rotten_flesh'
  ];

  let matA = [
    'kubejs:aluminum_budding_shard',
    'kubejs:awakened_draconium_budding_shard',
    'kubejs:bee_budding_shard',
    'kubejs:blaze_budding_shard',
    'kubejs:blazing_crystal_budding_shard',
    'kubejs:brass_budding_shard',
    'kubejs:bronze_budding_shard',
    'kubejs:certus_quartz_budding_shard',
    'kubejs:chaos_dragon_budding_shard',
    'kubejs:chicken_budding_shard',
    'kubejs:coal_budding_shard',
    'kubejs:constantan_budding_shard',
    'kubejs:copper_budding_shard',
    'kubejs:cow_budding_shard',
    'kubejs:creeper_budding_shard',
    'kubejs:diamond_budding_shard',
    'kubejs:draconium_budding_shard',
    'kubejs:electrum_budding_shard',
    'kubejs:emerald_budding_shard',
    'kubejs:enderman_budding_shard',
    'kubejs:energized_steel_budding_shard',
    'kubejs:fluix_budding_shard',
    'kubejs:fluorite_budding_shard',
    'kubejs:ghast_budding_shard',
    'kubejs:glow_squid_budding_shard',
    'kubejs:glowstone_budding_shard',
    'kubejs:gold_budding_shard',
    'kubejs:hop_graphite_budding_shard',
    'kubejs:iron_budding_shard',
    'kubejs:lapis_lazuli_budding_shard',
    'kubejs:lead_budding_shard',
    'kubejs:magma_cube_budding_shard',
    'kubejs:nether_quartz_budding_shard',
    'kubejs:netherite_budding_shard',
    'kubejs:nickel_budding_shard',
    'kubejs:niotic_crystal_budding_shard',
    'kubejs:nitro_crystal_budding_shard',
    'kubejs:osmium_budding_shard',
    'kubejs:phantom_budding_shard',
    'kubejs:prismarine_budding_shard',
    'kubejs:quantum_alloy_budding_shard',
    'kubejs:redstone_budding_shard',
    'kubejs:refined_glowstone_budding_shard',
    'kubejs:refined_obsidian_budding_shard',
    'kubejs:sculk_budding_shard',
    'kubejs:sheep_budding_shard',
    'kubejs:silver_budding_shard',
    'kubejs:skeleton_budding_shard',
    'kubejs:sky_steel_budding_shard',
    'kubejs:slime_budding_shard',
    'kubejs:snow_golem_budding_shard',
    'kubejs:spider_budding_shard',
    'kubejs:spirited_crystal_budding_shard',
    'kubejs:squid_budding_shard',
    'kubejs:steel_budding_shard',
    'kubejs:tin_budding_shard',
    'kubejs:uraninite_budding_shard',
    'kubejs:uranium_budding_shard',
    'kubejs:wither_budding_shard',
    'kubejs:nether_star_nugget',
    'kubejs:wither_skeleton_budding_shard',
    'kubejs:zinc_budding_shard',
    'kubejs:zombie_budding_shard',
];

  craftedItems.forEach((crafted, index) => {
    IRRebirth.shaped(Item.of(crafted), ["AAA", "AAA", "AAA"], {
      A: matA[index]
    });
  });
    IRRebirth.shapeless(
      Item.of('minecraft:honey_bottle'), 
        ['kubejs:bee_budding_shard',
          'minecraft:glass_bottle']
      )
    IRRebirth.shaped(
      Item.of('minecraft:egg'), 
        [
          'AA',
          'AA'
        ],
        {
          A: 'kubejs:chicken_budding_shard'
        }
      )
    IRRebirth.shaped(
      Item.of('minecraft:feather'), 
        [
          'AAA'
        ],
        {
          A: 'kubejs:chicken_budding_shard'
        }
      )
    IRRebirth.shaped(
      Item.of('minecraft:leather'), 
        [
          'AA',
          'AA'
        ],
        {
          A: 'kubejs:cow_budding_shard'
        }
      )
    IRRebirth.shaped(
      Item.of('minecraft:milk_bucket'), 
        [
          'AAA',
          'ABA',
          'AAA'
        ],
        {
          A: 'kubejs:cow_budding_shard',
          B: 'minecraft:bucket'
        }
      )
    IRRebirth.shaped(
      Item.of('minecraft:white_wool'), 
        [
          'AAA',
          'A A',
          'AAA'
        ],
        {
          A: 'kubejs:sheep_budding_shard'
        }
      )
    IRRebirth.shapeless(
      Item.of('minecraft:string'), 
        ['kubejs:spider_budding_shard',
          'kubejs:spider_budding_shard']
      )
    IRRebirth.shapeless(
      Item.of('kubejs:nether_star_nugget'), 
        ['minecraft:nether_star']
      )
});