ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.mekanism.combining('kubejs:blaze_clay', 'minecraft:clay_ball', 'minecraft:blaze_powder')
    IRRebirth.recipes.mekanism.combining(Item.of('ae2:quartz_glass', 4), '4x #c:glass_blocks', Item.of('ae2:certus_quartz_dust', 5))
    IRRebirth.recipes.mekanism.combining(Item.of('ae2:quartz_fiber', 6), Item.of('ae2:quartz_glass', 3), '3x #forge:wires/certus')
    IRRebirth.recipes.mekanism.combining(Item.of('create:brass_ingot', 2), '#forge:ingots/zinc', '#forge:ingots/copper')
    IRRebirth.recipes.mekanism.combining(Item.of('create:brass_ingot', 2), '#forge:ingots/copper', '#forge:ingots/zinc')
    IRRebirth.recipes.mekanism.combining(Item.of('immersiveengineering:ingot_constantan', 2), '#forge:ingots/copper', '#forge:ingots/nickel')
    IRRebirth.recipes.mekanism.combining(Item.of('immersiveengineering:ingot_constantan', 2), '#forge:ingots/nickel', '#forge:ingots/copper')
    IRRebirth.recipes.mekanism.combining(Item.of('immersiveengineering:ingot_electrum', 2), '#forge:ingots/silver', '#forge:ingots/gold')
    IRRebirth.recipes.mekanism.combining(Item.of('immersiveengineering:ingot_electrum', 2), '#forge:ingots/gold', '#forge:ingots/silver')
    IRRebirth.recipes.mekanism.combining(Item.of('mekanism:ingot_bronze', 4), '#forge:ingots/tin', '3x #forge:ingots/copper')
    IRRebirth.recipes.mekanism.combining(Item.of('mekanism:ingot_bronze', 4), '3x #forge:ingots/copper', '#forge:ingots/tin')
})