ServerEvents.recipes(IRRebirth => {
	let listOxidized = [
		'kubejs:oxidized_aluminum',
		'kubejs:oxidized_refined_obsidian',
		'kubejs:oxidized_certus_quartz',
		'kubejs:oxidized_steel',
		'kubejs:oxidized_prismarine',
		'kubejs:oxidized_lapis',
		'kubejs:oxidized_gold',
		'kubejs:oxidized_netherite',
		'kubejs:oxidized_fluix',
		'kubejs:oxidized_glowstone',
		'kubejs:oxidized_uraninite',
		'kubejs:oxidized_iron',
		'kubejs:oxidized_silver',
		'kubejs:oxidized_uranium',
		'kubejs:oxidized_redstone',
		'kubejs:oxidized_emerald',
		'kubejs:oxidized_nether_quartz',
		'kubejs:oxidized_nickel',
		'kubejs:oxidized_electrum',
		'kubejs:oxidized_bronze',
		'kubejs:oxidized_draconium',
		'kubejs:oxidized_diamond',
		'kubejs:oxidized_lead',
		'kubejs:oxidized_constantan',
		'kubejs:oxidized_brass',
		'kubejs:oxidized_graphite',
		'kubejs:oxidized_tin',
		'kubejs:oxidized_zinc',
		'kubejs:oxidized_awakened_draconium',
		'kubejs:oxidized_refined_glowstone',
		'kubejs:oxidized_copper',
		'kubejs:oxidized_energized_steel',
		'kubejs:oxidized_blazing_crystal',
		'kubejs:oxidized_niotic_crystal',
		'kubejs:oxidized_spirited_crystal',
		'kubejs:oxidized_nitro_crystal',
		'kubejs:oxidized_carbon',
		'kubejs:oxidized_fluorite',
		'kubejs:oxidized_amethyst',
		'kubejs:oxidized_sky_steel',
		'kubejs:oxidized_quantum_alloy',
		'kubejs:oxidized_osmium'
	];

	let listIrradiated = [
		'kubejs:irradiated_aluminum',
		'kubejs:irradiated_refined_obsidian',
		'kubejs:irradiated_certus_quartz',
		'kubejs:irradiated_steel',
		'kubejs:irradiated_prismarine',
		'kubejs:irradiated_lapis',
		'kubejs:irradiated_gold',
		'kubejs:irradiated_netherite',
		'kubejs:irradiated_fluix',
		'kubejs:irradiated_glowstone',
		'kubejs:irradiated_uraninite',
		'kubejs:irradiated_iron',
		'kubejs:irradiated_silver',
		'kubejs:irradiated_uranium',
		'kubejs:irradiated_redstone',
		'kubejs:irradiated_emerald',
		'kubejs:irradiated_nether_quartz',
		'kubejs:irradiated_nickel',
		'kubejs:irradiated_electrum',
		'kubejs:irradiated_bronze',
		'kubejs:irradiated_draconium',
		'kubejs:irradiated_diamond',
		'kubejs:irradiated_lead',
		'kubejs:irradiated_constantan',
		'kubejs:irradiated_brass',
		'kubejs:irradiated_graphite',
		'kubejs:irradiated_tin',
		'kubejs:irradiated_zinc',
		'kubejs:irradiated_awakened_draconium',
		'kubejs:irradiated_refined_glowstone',
		'kubejs:irradiated_copper',
		'kubejs:irradiated_energized_steel',
		'kubejs:irradiated_blazing_crystal',
		'kubejs:irradiated_niotic_crystal',
		'kubejs:irradiated_spirited_crystal',
		'kubejs:irradiated_nitro_crystal',
		'kubejs:irradiated_carbon',
		'kubejs:irradiated_fluorite',
		'kubejs:irradiated_amethyst',
		'kubejs:irradiated_sky_steel',
		'kubejs:irradiated_quantum_alloy',
		'kubejs:irradiated_osmium'
	];

    listIrradiated.forEach((Irradiated, index) => {
	IRRebirth.custom({
	    "type": "mekanism:fission",
	    "input": {
		    "gas": listOxidized[index],
    		"amount": 1
	    },
	    "output": {
		    "gas": Irradiated,
		    "amount": 1
	    },
	    "heat": 1
    })
});
})