ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.mekanism.injecting(Item.of('mekanism:ingot_bronze', 8), Item.of('#forge:ingots/copper', 3), {"amount": 1, "gas": 'kubejs:tin_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('mekanism:ingot_bronze', 8), Item.of('#forge:ingots/tin', 1), {"amount": 3, "gas": 'kubejs:copper_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_constantan', 4), Item.of('#forge:ingots/copper', 1), {"amount": 1, "gas": 'kubejs:nickel_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_constantan', 4), Item.of('#forge:ingots/nickel', 1), {"amount": 1, "gas": 'kubejs:copper_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_electrum', 4), Item.of('#forge:ingots/gold', 1), {"amount": 1, "gas": 'kubejs:silver_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_electrum', 4), Item.of('#forge:ingots/silver', 1), {"amount": 1, "gas": 'kubejs:gold_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('create:brass_ingot', 4), Item.of('#forge:ingots/copper', 1), {"amount": 1, "gas": 'kubejs:zinc_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('create:brass_ingot', 4), Item.of('#forge:ingots/zinc', 1), {"amount": 1, "gas": 'kubejs:copper_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('create:andesite_alloy_block', 1), Item.of('minecraft:andesite', 1), {"amount": 1, "gas": 'kubejs:zinc_gas'})
})