ServerEvents.recipes(IRRebirth => {
    IRRebirth.recipes.mekanism.injecting(Item.of('mekanism:ingot_bronze', 40), Item.of('#forge:ingots/copper', 30), {"amount": 1, "gas": 'kubejs:tin_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('mekanism:ingot_bronze', 40), Item.of('mekanism:ingot_tin', 10), {"amount": 3, "gas": 'kubejs:copper_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_constantan', 20), Item.of('#forge:ingots/copper', 10), {"amount": 1, "gas": 'kubejs:nickel_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_constantan', 20), Item.of('immersiveengineering:ingot_nickel', 10), {"amount": 1, "gas": 'kubejs:copper_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_electrum', 20), Item.of('#forge:ingots/gold', 10), {"amount": 1, "gas": 'kubejs:silver_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('immersiveengineering:ingot_electrum', 20), Item.of('immersiveengineering:ingot_silver', 10), {"amount": 1, "gas": 'kubejs:gold_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('create:brass_ingot', 20), Item.of('#forge:ingots/copper', 10), {"amount": 1, "gas": 'kubejs:zinc_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('create:brass_ingot', 20), Item.of('create:zinc_ingot', 10), {"amount": 1, "gas": 'kubejs:copper_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('create:andesite_alloy_block', 10), Item.of('minecraft:andesite', 10), {"amount": 1, "gas": 'kubejs:zinc_gas'})
    IRRebirth.recipes.mekanism.injecting(Item.of('kubejs:netherite_shard', 4), Item.of('minecraft:ancient_debris', 1), {"amount": 1, "gas": 'mekanism:hydrogen_chloride'})
    IRRebirth.recipes.mekanism.injecting(Item.of('kubejs:netherite_shard', 24), Item.of('kubejs:raw_netherite_block', 1), {"amount": 2, "gas": 'mekanism:hydrogen_chloride'})
    IRRebirth.recipes.mekanism.injecting(Item.of('kubejs:netherite_shard', 8), Item.of('kubejs:raw_netherite', 3), {"amount": 1, "gas": 'mekanism:hydrogen_chloride'})
})