ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ output: 'mekanism:ingot_osmium', type: 'minecraft:blasting'})
    IRRebirth.remove({ output: 'mekanism:ingot_osmium', type: 'minecraft:smelting'})
    IRRebirth.remove({output: 'ae2:certus_quartz_dust', type: 'mekanism:crushing'})
    IRRebirth.remove({ input: '#forge:ores/draconium', type: 'mekanism:enriching'})
    IRRebirth.remove({ input: 'create:crushed_raw_osmium'})
    IRRebirth.remove({output: 'ae2:fluix_dust', type: 'mekanism:crushing'})
    IRRebirth.remove({ output: 'mekanism:enriched_carbon'})
    IRRebirth.remove({ id: 'mekanism:infusion_conversion/carbon/from_charcoal'})
    IRRebirth.remove({ id: 'mekanism:infusion_conversion/carbon/from_coal_block'})
    IRRebirth.remove({ id: 'mekanism:infusion_conversion/carbon/from_coal'})
    IRRebirth.remove({ id: 'mekanism:infusion_conversion/carbon/from_charcoal_block'})
    IRRebirth.remove({ output: 'mekanism:digital_miner'})
    IRRebirth.remove({ output: 'mekanism:hdpe_rod'})
})