LootJS.modifiers((IRRebirth) => {
  IRRebirth
    .addLootTypeModifier(LootType.CHEST)
    .removeLoot(["draconicevolution:draconium_ingot",
      "draconicevolution:draconium_dust"
    ]);
  IRRebirth
    .addLootTypeModifier(LootType.ENTITY)
    .removeLoot(["draconicevolution:draconium_ingot",
    "draconicevolution:draconium_dust"
  ]);
  IRRebirth
    .addLootTypeModifier(LootType.UNKNOWN)
    .removeLoot(["draconicevolution:draconium_ingot",
    "draconicevolution:draconium_dust"
  ]);
  IRRebirth
    .addLootTypeModifier(LootType.BLOCK)
    .removeLoot(["draconicevolution:draconium_ingot",
    "draconicevolution:draconium_dust"
  ]);
  IRRebirth
    .addLootTypeModifier(LootType.FISHING)
    .removeLoot(["draconicevolution:draconium_ingot",
    "draconicevolution:draconium_dust"
  ]);
  IRRebirth
    .addLootTypeModifier(LootType.GIFT)
    .removeLoot(["draconicevolution:draconium_ingot",
    "draconicevolution:draconium_dust"
  ]);

});