ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ mod: 'prefab' })
    IRRebirth.remove({ output: 'minecraft:chest'})
    IRRebirth.remove({ output: 'minecraft:stick'})
    IRRebirth.remove({ output: 'immersiveengineering:alloybrick'})
    IRRebirth.remove({ output: 'storagenetwork:single_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:inventory_remote'})
    IRRebirth.remove({ output: 'storagenetwork:crafting_remote'})
    IRRebirth.remove({ output: 'storagenetwork:picker_remote'})
    IRRebirth.remove({ output: 'storagenetwork:collector_remote'})
    IRRebirth.remove({ output: 'storagenetwork:builder_remote'})
    IRRebirth.remove({ output: 'storagenetwork:expanded_remote'})
    IRRebirth.remove({ output: 'storagenetwork:filter_kabel'})
    IRRebirth.remove({ output: 'storagenetwork:request_expanded'})
    IRRebirth.remove({ output: 'storagenetwork:import_filter_kabel'})
    IRRebirth.remove({ output: 'storagenetwork:exchange'})
    IRRebirth.remove({ output: 'storagenetwork:collector'})
    IRRebirth.remove({ output: 'storagenetwork:stack_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:speed_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:slow_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:stock_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:operation_upgrade'})
    IRRebirth.remove({ input: 'sophisticatedbackpacks:magnet_upgrade'})
    IRRebirth.remove({ input: 'sophisticatedbackpacks:advanced_magnet_upgrade'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/treated_wood_horizontal'})
    IRRebirth.remove({ output: 'immersiveengineering:hammer'})
    IRRebirth.remove({ output: 'create:brass_casing'})
    IRRebirth.remove({ output: '#create:sandpaper'})
    IRRebirth.remove({ output: 'immersiveengineering:stick_iron', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ output: 'immersiveengineering:stick_steel', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ output: 'immersiveengineering:stick_aluminum', type: "minecraft:crafting_shaped"})
    IRRebirth.remove({ output: 'create:copper_casing'})
    IRRebirth.remove({ id: 'immersiveengineering:crafting/cokebrick'})
    IRRebirth.remove({ id: 'create:crafting/kinetics/empty_blaze_burner'})
    IRRebirth.remove({ mod: 'ftbquests' })
    IRRebirth.remove({ output: 'ftbfiltersystem:smart_filter'})
    IRRebirth.remove({ output: 'wstweaks:lava_blade'})
    IRRebirth.remove({ output: 'wstweaks:blaze_blade'})
    IRRebirth.remove({ mod: 'jamd' })
})