ServerEvents.recipes(IRRebirth => {
    IRRebirth.remove({ mod: 'prefab' })
    IRRebirth.remove({ output: 'storagenetwork:single_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:inventory_remote'})
    IRRebirth.remove({ output: 'storagenetwork:crafting_remote'})
    IRRebirth.remove({ output: 'storagenetwork:picker_remote'})
    IRRebirth.remove({ output: 'storagenetwork:collector_remote'})
    IRRebirth.remove({ output: 'storagenetwork:builder_remote'})
    IRRebirth.remove({ output: 'storagenetwork:expanded_remote'})
    IRRebirth.remove({ output: 'storagenetwork:filter_kabel'})
    IRRebirth.remove({ output: 'storagenetwork:request_expanded'})
    IRRebirth.remove({ output: 'storagenetwork:import_filter_kabel'})
    IRRebirth.remove({ output: 'storagenetwork:exchange'})
    IRRebirth.remove({ output: 'storagenetwork:collector'})
    IRRebirth.remove({ output: 'storagenetwork:stack_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:speed_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:slow_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:stock_upgrade'})
    IRRebirth.remove({ output: 'storagenetwork:operation_upgrade'})
    IRRebirth.remove({ input: 'sophisticatedbackpacks:magnet_upgrade'})
    IRRebirth.remove({ input: 'sophisticatedbackpacks:advanced_magnet_upgrade'})
    IRRebirth.remove({ mod: 'ftbquests' })
    IRRebirth.remove({ output: 'ftbfiltersystem:smart_filter'})
    IRRebirth.remove({ output: 'wstweaks:lava_blade'})
    IRRebirth.remove({ output: 'wstweaks:blaze_blade'})
    IRRebirth.remove({ mod: 'jamd' })
    IRRebirth.remove({ output: ['quarryplus:solid_fuel_quarry', 'quarryplus:mining_well', 'quarryplus:book_mover', 'quarryplus:pump_plus', 'quarryplus:replacer', 'quarryplus:exp_pump', 'quarryplus:adv_quarry', 'quarryplus:mini_quarry', 'quarryplus:filler', 'quarryplus:waterlogged_marker', 'quarryplus:waterlogged_flex_marker', 'quarryplus:waterlogged_marker16', 'quarryplus:placer_plus', 'quarryplus:remote_placer', 'quarryplus:spawner_controller', 'quarryplus:frame', 'quarryplus:creative_generator', 'quarryplus:status_checker', 'quarryplus:y_setter', 'quarryplus:replacer_module', 'quarryplus:exp_module', 'quarryplus:remove_bedrock_module', 'quarryplus:fuel_module_normal', 'quarryplus:filler_module', 'quarryplus:repeat_tick_module', 'quarryplus:dummy', 'quarryplus:dummy_replacer']})
    IRRebirth.remove({ output: 'quarryplus:workbench'})
    IRRebirth.remove({ id: 'utilitarian:utility/logs_to_sticks'})
    IRRebirth.remove({ id: 'utilitarian:utility/logs_to_chests'})
    IRRebirth.remove({ output: 'explorerscompass:explorerscompass'})
})